---
apiVersion: v1
kind: Secret
metadata:
  name: db-creds
type: Opaque
stringData:
  conjur-map: |-
    dbaddr: test/CityApp/DBAccount/address
    dbuser: test/CityApp/DBAccount/username
    dbpass: test/CityApp/DBAccount/password
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-conjurtok8ssecret
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-conjurtok8ssecret-init
  labels:
    app: cityapp-conjurtok8ssecret-init
spec:
  ports:
  - port: 80
    nodePort: 30085
    name: http
  selector:
    app: cityapp-conjurtok8ssecret-init
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-conjurtok8ssecret-init
  name: cityapp-conjurtok8ssecret-init
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-conjurtok8ssecret-init
  template:
    metadata:
      labels:
        app: cityapp-conjurtok8ssecret-init
    spec:
      serviceAccountName: cityapp-conjurtok8ssecret
      hostAliases:
      - ip: "{LAB_IP}"
        hostnames:
        - "{DB_HOST}"
      containers:
      - name: cityapp
        image: localhost/cityapp:php
        imagePullPolicy: IfNotPresent
        env:
          - name: DEMO_METHOD
            value: push-to-k8s-secret-init
        volumeMounts:
          - name: conjur-access-token
            mountPath: /conjur
            readOnly: true
          - name: secret-volume
            mountPath: /etc/secret-volume
      initContainers:
      - name: conjurtok8ssecretinit
        image: docker.io/cyberark/secrets-provider-for-k8s:1.10.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: jwt-token
          mountPath: /var/run/secrets/tokens
        - mountPath: /run/conjur
          name: conjur-access-token
        - mountPath: /etc/conjur/ssl
          name: conjur-certs
        - mountPath: /conjur/podinfo
          name: podinfo
        env:
        - name: JWT_TOKEN_PATH
          value: /var/run/secrets/tokens/jwt
        - name: CONTAINER_MODE
          value: init
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_SECRETS
          value: db-creds
        - name: SECRETS_DESTINATION
          value: k8s_secrets
        envFrom:
          - configMapRef:
              name: apps-cm
      volumes:
        - name: secret-volume
          secret:
            secretName: db-creds
        - name: podinfo
          downwardAPI:
            items:
              - path: annotations
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: conjur-certs
          emptyDir:
            medium: Memory
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: '{JWT_AUDIENCE}'
