---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cityapp-springboot-native
---
apiVersion: v1
kind: Service
metadata:
  name: cityapp-springboot-native
  labels:
    app: cityapp-springboot-native
spec:
  ports:
  - port: 8080
    nodePort: 30088
    name: http
  selector:
    app: cityapp-springboot-native
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityapp-springboot-native
  name: cityapp-springboot-native
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityapp-springboot-native
  template:
    metadata:
      labels:
        app: cityapp-springboot-native
    spec:
      serviceAccountName: cityapp-springboot-native
      hostAliases:
      - ip: "{LAB_IP}"
        hostnames:
        - "{DB_HOST}"
        - "{CONJUR_LEADER_HOST}"
      containers:
      - name: cityapp
        image: localhost/cityapp-springboot:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: DB_HOST
            value: 'null'        
          - name: DB_USER
            value: 'null'
          - name: DB_PASS
            value: 'null'
          - name: DB_PORT
            value: '3306'
          - name: DB_NAME
            value: world
          - name: CONJUR_JWT_TOKEN_PATH
            value: /var/run/secrets/tokens/jwt
          - name: CONJUR_AUTHENTICATOR_ID
            value: k8s
          - name: CONJUR_MAPPING_DB_HOST
            value: test/CityApp/DBAccount/address
          - name: CONJUR_MAPPING_DB_USER
            value: test/CityApp/DBAccount/username
          - name: CONJUR_MAPPING_DB_PASS
            value: test/CityApp/DBAccount/password
        envFrom:
          - configMapRef:
              name: apps-springboot-cm
        volumeMounts:
        - mountPath: /var/run/secrets/tokens
          name: jwt-token
      volumes:
        - name: jwt-token
          projected:
            sources:
              - serviceAccountToken:
                  path: jwt
                  expirationSeconds: 6000
                  audience: '{JWT_AUDIENCE}'
